spring.application.name=floricultura

# URL de conexão do Azure SQL Server (Corrigida com //)
# URL de conexão do Azure SQL Server (Note o ponto e vírgula após a URL do servidor)
spring.datasource.url=jdbc:sqlserver://${DATA_BASE_URL};databaseName=${DATA_BASE_NAME};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
# Credenciais de acesso
spring.datasource.username=${DATA_BASE_USER}
spring.datasource.password=${DATA_BASE_PASSWORD}

# Configurações do Driver e Hibernate
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true