spring.application.name=floricultura
# URL de conexão do Azure SQL Server
spring.datasource.url=jdbc:sqlserver:bd-blowourway.database.windows.net;database=nome_do_seu_banco;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

# Credenciais de acesso
spring.datasource.username=bdblowyourway
spring.datasource.password=Blow010203

# Configurações do Driver e Hibernate
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true